config/routes.rb
Planet::Application.routes.draw do

  match 'search' => 'pages#search'

  
  resources :pages do
    collection do 
      get :show 
      get :index
      get :channels
    end
  end
  
  resources :feed_urls

  root :to => "pages#index"  

end

app/models/feed_url.rb
class FeedUrl < ActiveRecord::Base
  has_many :feeds, :dependent => :delete_all
  validates_presence_of :feed_url
  validates_presence_of :title

  def process_feed(xml)
    doc = Hpricot.XML(xml)
    if doc.search(:rss).size > 0
      process_rss(doc)
      return 'rss'
    elsif doc.search(:feed).size > 0
      process_atom(doc)
      return 'atom'
    else
      raise RuntimeError, 'Unknown feed type only RSS and Atom can be read'
    end
  end

  # Process rss feed and saves it into db
  def process_rss(rss)
    time_offset = 1

    # taking out site/blog link and title.
    site_link = (rss/:channel/:link).first.inner_html
    site_title = (rss/:channel/:title).first.inner_html
    puts "processing rss for #{site_link}"

    (rss/:channel/:item).each do |item|
      link_raw = item.%('feedburner:origLink') || item.%('link') || (item/:link)
      link = link_raw.inner_html

      if (Feed.find_by_link(link)).blank?
        rss_feed = Feed.new
        rss_feed.feed_url = self
        rss_feed.site_link = site_link
        rss_feed.site_title = site_title
        rss_feed.title = (item/:title).inner_html
        rss_feed.link = link
        rss_feed.author = (item/:author).inner_html
        rss_feed.content = (item/:description).inner_html
        if !(item/"content:encoded").blank?
          rss_feed.content = (item/"content:encoded").inner_html
        else
          rss_feed.content = (item/:description).inner_html
        end

        rss_feed.published = (item/:pubDate).inner_html

        if rss_feed.published.blank?
          # if !(rss/:channel/:lastBuildDate).inner_html.blank?
          #            puts "rss feed published time blank. taking lastBuildDate one"
          #            puts (rss/:channel/:lastBuildDate).inner_html
          #            time = (rss/:channel/:lastBuildDate).inner_html
          #            rss_feed.published = Time.parse(time).to_s(:db)
          #          else
          puts "rss feed published time blank. calculating system one."
          # taking it 20 days back..
          rss_feed.published = (Time.now - (20*60*60*24) - time_offset.hours).to_s(:db)
          time_offset += 1
          # end
        end

        rss_feed.title = htmlize(rss_feed.title)
        rss_feed.content = htmlize(rss_feed.content, link)
        rss_feed.save!
      end
    end
  end

  # Process atom feed and saves it into db
  def process_atom(atom)
    time_offset = 1

    # taking out site/blog link and title.
    site_link =  (atom/:feed).search(:link)[1]['href']
    site_title = (atom/:feed/:title).first.inner_html

    puts "processing atom for #{site_link}"

    (atom/:entry).each do |item|
      link_raw = item.%('feedburner:origLink') || item.%('link')

      if !link_raw.blank?
        link = (link_raw).inner_html
      else
        link = (item/:link).attr('href')
      end

      if (Feed.find_by_link(link)).blank?
        atom_feed = Feed.new
        atom_feed.feed_url = self
        atom_feed.site_link = site_link
        atom_feed.site_title = site_title
        atom_feed.title = (item/:title).inner_html
        atom_feed.link = link
        atom_feed.author = (item/:author/:name).inner_html
        atom_feed.content = (item/:content).inner_html
        atom_feed.published = (item/:published).inner_html

        if atom_feed.content.blank?
          atom_feed.content =  (item/:summary).inner_html
        end

        if atom_feed.published.blank?
          atom_feed.published =  (item/:updated).inner_html
        end

        if atom_feed.published.blank?
          # taking it 20 days back..
          atom_feed.published =  (Time.now - (20*60*60*24) - time_offset.hours).to_s(:db)
          time_offset += 1
        end

        atom_feed.title = htmlize(atom_feed.title)
        atom_feed.content = htmlize(atom_feed.content, link)
        atom_feed.save!
      end
    end
  end

  # Fetches RSS feed and returns back xml
  def fetch_feed
    rss = ""
    begin
      f = open(self.feed_url, 'r')
      rss = f.read()
      f.close
    rescue Exception => e
      puts e.message
      puts "FeedUrl::fetch_feed :: Error in opening feed"
    end
    return rss
  end

  # htmlize the html codes back.
  def htmlize(string, link=nil)
    string.gsub!('&lt;', '<')
    string.gsub!('&gt;', '>')
    string.gsub!('&amp;', '&')
    string.gsub!('&#39;', "'")
    string.gsub!('&quot;', '"')
    string.gsub!('<![CDATA[', '')
    string.gsub!(']]>', '')

    # for image srcs like <img src="/assets/2008/4/23/rails3.jpg_1208810865" />"
    # adding host so that they become valid
    # "<img src="http://www.google.com/assets/2008/4/23/rails3.jpg_1208810865" />"
    if link
      host = URI.parse(link).host
      if host != "feeds.feedburner.com"
        string.gsub!("src=\"/", "src=\"http://"+host+"/")
      end
    end
    return string
  end

  ## Removed duplicate entries
  ## Currently based on feed title. #TODO make it more correct.
  def self.cleanup_feeds
    feed_records = FeedUrl.find_by_sql("select count(title) as qty, feeds.id as feed_id from feeds group by title having qty > 1;")
    feed_ids = (feed_records.collect{|i| i.feed_id})
    Feed.delete(feed_ids)
  end
end

app/controllers/feed_urls_controller.rb
class FeedUrlsController < ApplicationController
  before_filter :authenticate
  
  # GET /feed_urls
  # GET /feed_urls.json
  def index
    @feed_urls = FeedUrl.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feed_urls }
    end
  end

  # GET /feed_urls/1
  # GET /feed_urls/1.json
  def show
    @feed_url = FeedUrl.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feed_url }
    end
  end

  # GET /feed_urls/new
  # GET /feed_urls/new.json
  def new
    @feed_url = FeedUrl.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feed_url }
    end
  end

  # GET /feed_urls/1/edit
  def edit
    @feed_url = FeedUrl.find(params[:id])
  end

  # POST /feed_urls
  # POST /feed_urls.json
  def create
    @feed_url = FeedUrl.new(params[:feed_url])

    respond_to do |format|
      if @feed_url.save
        format.html { redirect_to @feed_url, notice: 'Feed url was successfully created.' }
        format.json { render json: @feed_url, status: :created, location: @feed_url }
      else
        format.html { render action: "new" }
        format.json { render json: @feed_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feed_urls/1
  # PUT /feed_urls/1.json
  def update
    @feed_url = FeedUrl.find(params[:id])

    respond_to do |format|
      if @feed_url.update_attributes(params[:feed_url])
        format.html { redirect_to @feed_url, notice: 'Feed url was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feed_urls/1
  # DELETE /feed_urls/1.json
  def destroy
    @feed_url = FeedUrl.find(params[:id])
    @feed_url.destroy

    respond_to do |format|
      format.html { redirect_to feed_urls_url }
      format.json { head :ok }
    end
  end
  
  def login
    session[:authenticated] = true
    render :text => "You have successfully logged in. <a href='/blog'>Back</a>"
  end

  # One way to logout from http authentication.
  # But it is specific to some browsers. So it won't work always.
  def logout
    render :text => "You logged out. <a href='/blog'>Back</a>", :status => 401
    session[:authenticated] = false
  end

  protected
  def authenticate
    authenticate_or_request_with_http_basic do | user_name, password|
      pwd = YAML::load_file("/etc/password.yml")["type"]["password"]
      user_name == "anil" && password == pwd
    end
  end  
end

app/helpers/feed_urls_helper.rb
module FeedUrlsHelper
end

app/views/feed_urls/_form.html.erb
<%= form_for(@feed_url) do |f| %>
  <% if @feed_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed_url.errors.count, "error") %> prohibited this feed_url from being saved:</h2>

      <ul>
      <% @feed_url.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :site_url %><br />
    <%= f.text_field :site_url %>
  </div>
  <div class="field">
    <%= f.label :feed_url %><br />
    <%= f.text_field :feed_url %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :star %><br />
    <%= f.check_box :star %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feed_urls/edit.html.erb
<h1>Editing feed_url</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed_url %> |
<%= link_to 'Back', feed_urls_path %>

app/views/feed_urls/index.html.erb
<h1>Listing feed_urls</h1>

<table>
  <tr>
    <th>Site url</th>
    <th>Feed url</th>
    <th>Title</th>
    <th>Star</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feed_urls.each do |feed_url| %>
  <tr>
    <td><%= feed_url.site_url %></td>
    <td><%= feed_url.feed_url %></td>
    <td><%= feed_url.title %></td>
    <td><%= feed_url.star %></td>
    <td><%= link_to 'Show', feed_url %></td>
    <td><%= link_to 'Edit', edit_feed_url_path(feed_url) %></td>
    <td><%= link_to 'Destroy', feed_url, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feed url', new_feed_url_path %>

app/views/feed_urls/new.html.erb
<h1>New feed_url</h1>

<%= render 'form' %>

<%= link_to 'Back', feed_urls_path %>

app/views/feed_urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Site url:</b>
  <%= @feed_url.site_url %>
</p>

<p>
  <b>Feed url:</b>
  <%= @feed_url.feed_url %>
</p>

<p>
  <b>Title:</b>
  <%= @feed_url.title %>
</p>

<p>
  <b>Star:</b>
  <%= @feed_url.star %>
</p>


<%= link_to 'Edit', edit_feed_url_path(@feed_url) %> |
<%= link_to 'Back', feed_urls_path %>